### ISSUE TITLE
Can not get commands registered

### ISSUE THREAD

**Issue by bariscicek** [carlosrocha/vim-chrome-devtools#2]
I am having hard time installing this remote plugin. 

I tried to install it manually. I am not using Vplug or similar so I just cloned the repository to ~/.config/nvim/rplugin/node and also I have node-host installed (healthcheck confirms that). 

When I try the _UpdateRemotePlugins_ command nvim registers the plugin and generate the manifest file.

However there is no command in that manifest file, just a basic line as follows:
`
 " node plugins                                                                                                          
call remote#host#RegisterPlugin('node', '/home/baris/.config/nvim/rplugin/node/vim-chrome-devtools', [                   \ ])   
`
As expected _ChromeDevToolsConnect_ method is not understood. 

I did run both npm install && npm run build. 

Not sure what I can inspect further.

**Comment by carlosrocha** [comment]
Did you ran the commands `npm install && npm run build` on the folder `/home/baris/.config/nvim/rplugin/node/vim-chrome-devtools`? It should generate a `lib/` folder if it runs successfully.

**Comment by andreasthoelke** [comment]
Hi! I think I'm running into a similar issue.

Following the instructions in the readme, using:
`Plug 'carlosrocha/vim-chrome-devtools', { 'do': 'npm install && npm run build' }`

Then running `:UpdateRemotePlugins` outputs:
```
remote/host: node host registered plugins ['vim-chrome-devtools']
remote/host: generated rplugin manifest: /Users/andreas.thoelke/.local/share/nvim/rplugin.vim
```

After restarting nvim `:ChromeDevToolsConnect` is not available.

`.local/share/nvim/rplugin.vim` has:
```
" node plugins
call remote#host#RegisterPlugin('node', '/Users/andreas.thoelke/.vim/plugged/vim-chrome-devtools', [
    \ ])


" python3 plugins

..
```
`checkhealth` shows:
```## Node.js provider (optional)
- INFO: Node.js: v11.1.0
- INFO: Neovim node.js host: /Users/andreas.thoelke/.npm/lib/node_modules/neovim/bin/cli.js
- OK: Latest "neovim" npm/yarn package is installed: 4.2.1
```

`~/.vim/plugged/vim-chrome-devtools` has a `lib/` folder:

![image](https://user-images.githubusercontent.com/6566914/51612972-cf5f7700-1f22-11e9-894f-63471ce28402.png)

Also uninstalling via `PlugClean` never finishes/crashes nvim. Is that because of the sym-links?
